import { generate } from "rxjs"

export const BASE_URL = 'https://vahanapi.ais140.com/api/'
export const API_CONSTANT = {
    login:'Auth/Login',
    adminManufacturerList : 'Manufacturer/ManufacturerList',
    stateDropdown:'State/StateList',
    cityDropdown:'State/CityList',
    userProfileDetail:'Profile/GetUserProfileList',
    updateUser:'Profile/UpdateUserProfile',
    updateUserImage:'Profile/UpdateUserProfileImage',
    sendEmailOtp:'Profile/SendEmailOTP',
    veryEmailMobile:'Profile/VerifyEmailOTP',
    sendMobileOtp:'Profile/SendMobileOTP',
    createState:'State/AddState',
    addCity:'City/AddCityData',
    createManufacture:'Manufacturer/AddManufacturer',
    updateManufacture:'Manufacturer/UpdateManufacturer',
    distributerList:'Distributor/DistributorList',
    createDistributer:'Distributor/AddDistributor',
    updateDistributer:'Distributor/UpdateDistributor',
    certificateList :'Manufacturer/ManufacturerCertificateList',
    productList:'Product/GetProductList',
    authorityList:'Authority/GetAuthorityList',
    updateCertificate:'Manufacturer/UpdateManufacturerCertificate',
    uploadCertificate:'Manufacturer/UploadManufacturerCertificate',
    dealerList:'Dealer/GetDealerList',
    createDealer:'Dealer/AddDealer',
    updateDealer:'Dealer/UpdateDealer',
    distributerDropdown:'Common/GetDistributorListById',
    stockList : 'Device/GetVahanDeviceList',
    addSingleStock : 'Device/AddVahanDevice',
    addBulkStock : 'Device/UploadDeviceData?fk_manufacture_id=${manufactureId}&fk_device_type_id=${productId}',
    updateStock:'Device/UpdateVahanDevice',
    deviceList : 'Device/GetVahanDeviceSimStatusList',
    orderDashboard:'Request/GetRequestDashboard',
    orderProductList: 'DeviceSubCategory/GetDeviceSubCategoryList',
    stateListOnDeviceType :'Common/GetStateListOnDeviceType',
    planBasedOnState :'Common/GetPlanListBasedOnState',
    generateOrder :'Request/GenerateRequest',
    modifydevice:'Device/ModifySimInformation?iccid=${iccid}',
    managerList:'SalesManager/GetSalesManagerList',
    addManager:'SalesManager/AddSalesManager',
    updateManager:'SalesManager/UpdateSalesManager',
    salesList:'SalesManager/vahanSalesList',
    createSales:'SalesManager/vahanSales',
    deviceBalance:'SalesManager/CheckDeviceBalance',
    backendList:'Backend/BackendList',
    createBackend:'Backend/AddBackend',
    updateBackend:'Backend/UpdateBackend',
    stateList:'State/StateList',
    updateState:'State/UpdateState',
    cityList:'State/CityList',
    updateCity:'City/UpdateCityData',
    addProduct:'Product/AddProductData',
    updateProduct:'Product/UpdateProductData',
    rtoList:'RTO/RTOList',
    createRto:'RTO/AddRTO',
    updateRto:'RTO/UpdateRTO',
    addAuthority:'Authority/AddAuthorityData',
    updateAuthority:'Authority/UpdateAuthorityData',
    authorityPlanList:'AuthorityPlan/GetAuthorityPlanList',
    addAuthorityPlan:'AuthorityPlan/AddAuthorityPlanData',
    updateAuthorityPlan:'AuthorityPlan/UpdateAuthorityPlanData',
    categoryList:'DeviceCategory/GetDeviceCategoryList',
    createCategory:'DeviceCategory/AddDeviceCategoryData',
    updateCategory:'DeviceCategory/UpdateDeviceCategoryData',
    subCategoryList:'DeviceSubCategory/GetDeviceSubCategoryList',
    createSubCategory:'DeviceSubCategory/AddDeviceSubCategoryData',
    updateSubCategory:'DeviceSubCategory/UpdateDeviceSubCategoryData',
    gstList:'GST/GetGSTList',
    requestById : 'Request/GetRequestById',
    shippingAdderss : 'Shipping/GetShippingAddressList',
    interIntraStatus :'Request/GetInterIntraStatusById',
    deviceVahanList :"Device/GetVahanDeviceList",
    generateInvoice:'Billing/GenerateInvoice',
    shippingList :'Shipping/GetShippingAddressList',
    addShippingAddress :'Shipping/AddShippingAddress',
    updateShippingAddress :'Shipping/UpdateShippingAddress',
    deleteShippingAddress :'Shipping/DeleteShippingAddress',
    hsnList:'GST/GetGSTList',
    addHsn:'GST/CreateGST',
    updateHsn:'GST/UpdateGST',
    complainList:'Compliant/GetDeviceComplaintList',
    addComplain:'Compliant/AddDeviceComplaint',
    updateComplain:'Compliant/UpdateDeviceComplaint',
    serviceList:'Service/GetDeviceServiceList',
    createService:'Service/AddDeviceService',
    updateService:'Service/UpdateDeviceService',
    headListDD:'Support/GetSupportHeadList',
    supportList:'Support/GetSupportMemberList',
    addSupport:'Support/AddSupportMember',
    updateSupport:'Support/UpdateSupportMember',
    activationDetail:'Device/GetVahanSubInfo',
    activationList:'Device/VahanActivationRequestList',
    updateMis:'Device/vahan_update_misdetail',
    updateSim:'Device/vahan_update_simdetail',
    updateStatus:'Device/vahan_update_ar_request_status',
    certificatedata:'Device/vahan_vehicle_certificate_upload',
    deleteListData:'Device/vahan_vehicle_ar_request_delete',
    updateActivation:'Device/AddVahanSubInfo',
    vehicleType:'Device/GetVahanRegistrationTypeList',
    inventoryList:'Device/GetUserDeviceInventory',
    paymentMode:'Common/GetPaymentModeList',
    getTaxCalculation:'Request/GetTaxCalculation',
    updateRazorPaymentAsync :'Request/UpdateRazorPaymentAsync',
    itemIssue :'Billing/ItemIssue',
    orderHistory : 'Request/GetOrderRequestDetails',
    UpdateRequestOrderStatus : 'Request/UpdateRequestOrderStatus',
    paymentDetails :'Request/GetOrderPaymentDetails',
    paymentStatusList :'Common/GetPaymentStatusList',
    UpdateRequestPaymentStatus:'Request/UpdateRequestPaymentStatus',
    commonDealer : 'Common/GetDealerList',
    vahanList :'Vahan/GetVahanDataList',
    vahanSubList :'Vahan/GetVahanSubDataList',
    rawData : 'Vahan/GetDeviceRawData',
    getServiceDashboardData :'DeviceRequest/GetServiceDashboard',
    serviceddList : 'Common/GetServiceDDList',
    requestDeviceList:'Device/GetUserDeviceInventoryAll',
    generateRequest:'DeviceRequest/GenerateRequest',
    generateServiceInvoice:'DeviceRequest/GenerateServiceInvoice',
    generateServicePayment :'DeviceRequest/GeneratePayment',
    updateRequestStatus:'DeviceRequest/UpdateServiceStatus',
    orderRequestHistory:'',
    paymentRequestDetails:'DeviceRequest/GetOrderPaymentDetails',
    verifyRequestPayment:'DeviceRequest/VerifyPaymentbyAccount',
    getComplainDashboard:'UserComplaint/ComplaintDashboard',
    newComplainRequest:'UserComplaint/NewComplaintRequest',
    refrenceTypeDD:'Common/GetRefTypeDDList',
    priorityListDD:'Common/GetPriorityDDList',
    complainCategoryListDD:'Common/GetComplaintDDList',
    getSupportTeamList:'UserComplaint/GetSupportTeamList',
    assignComplain:'UserComplaint/assignComplaint',
    responseComplain:'UserComplaint/complaintResponse',
    userComplainList:'UserComplaint/ComplaintDashboardUser',
    oldComplainList:'UserComplaint/OldComplaintRequest',
    uploadInventory:'SalesManager/vahanDeviceUpload?uploadId=${uploadId}',
    validateFile:'SalesManager/vahanDeviceUploadValidate?uploadId=${uploadId}',
    docketNo:'SalesManager/updateDocketNumber',
    deleteSalesList:'SalesManager/deleteVahanSalesById',
    inventoryOrderDetail:'SalesManager/vahanDeviceUploadList',
    updateSales:'SalesManager/updateVahanSales',
    deviceListV2 : 'Device/GetVahanDeviceSimStatusListV2',
    vahanSearch:'Vahan/VahanSearch',
    deleteManufacture:'Manufacturer/DeleteManufacturer',
    deleteDistributer:'Distributor/DeleteDistributor',
    deleteDealer:'Dealer/DeleteDealer',
    manufactureListDD:'Common/GetManufacturerDDLList/{userId}',
    distributerListDD:'Common/GetDistributorDDLList/{userId}',
    dealerListDD:'Common/GetDealerDDLList/{userId}',
    deviceListByUserId:'Device/GetDeviceListByRoleUserId',
    simTypeList:'Common/GetSimTypeList',
    simUpdate:'Device/vahan_sim_provider_update',

    // manufacture device start here
    manufactureDashboard:'Inventory/ManufacturerDashboard',
    transferDevice:'Inventory/ManufacturerToDistributerInventoryTransfer',
    transferManualDevice:'Inventory/ManufacturerToDistributentoryTransferByList/{parentId}/{childId}',
    deleteManufactureDevice:'Device/vahan_device_unlink',

    // device plan category start api here
    planCategoryList:'DevicePlan/GetPlanCategoryList',
    createPlanCategory:'DevicePlan/CreatePlanCategory',
    updatePlanCategory:'DevicePlan/UpdatePlanCategory',
    deletePlanCategory:'DevicePlan/DeletePlanCategory',

    // device plan Sub category start api here
    planSubCategoryList:'DevicePlanSubCategory/GetPlanSubCategoryList',
    planSubCategoryById:'DevicePlanSubCategory/GetPlanSubCategoryList/{categoryId}/{subcategoryId}',
    createPlanSubCategory:'DevicePlanSubCategory/CreatePlanSubCategory',
    updatePlanSubCategory:'DevicePlanSubCategory/UpdatePlanSubCategory',
    deletePlanSubCategory:'DevicePlanSubCategory/DeletePlanSubCategory',

    // device plan start api here
    devicePlanList:'CustomerPlan/CustomerPlanList/{custId}',
    createDevicePlan:'CustomerPlan/CustomerPlanCreate',
    updateDevicePlan:'CustomerPlan/CustomerPlanUpdate',
    deleteDevicePlan:'CustomerPlan/CustomerPlanDelete',

    // menu master start api here
    menuMasterList:'MenuMaster/getMenuMasterList',
    menuMasterById:'MenuMaster/getMenuMasterById',
     createMenuMaster:'MenuMaster/AddMenuMaster',
     updateMenuMaster:'MenuMaster/UpdateMenuMaster',
     deleteMenuMaster:'MenuMaster/DeleteMenuMaster',

      // sub menu master start api here
    subMenuMasterList:'SubMenuMaster/getSubMenuMasterList',
    subMenuMasterById:'SubMenuMaster/getSubMenuMasterById',
     createSubMenuMaster:'SubMenuMaster/AddSubMenuMaster',
     updateSubMenuMaster:'SubMenuMaster/UpdateSubMenuMaster',
     deleteSubMenuMaster:'SubMenuMaster/DeleteSubMenuMaster',

    // wallet api start here 
    walletUserList:'Wallet/GetUserWallet',
    createUserWallet:'Wallet/CreateUserWallet',
    addMoney:'Wallet/AddMoneyWallet',
    walletLedgerList:'Wallet/GetUserWalletLedger',

    // SR request api here 
    planRatelist:'SRequest/GetUserPlanRateList/{category_id}/{sub_category_id}/{device_type_id}/{sim_type_id}',
    generateSimRequest:'SRequest/GenerateSimRequest',
    checkStatus:'SRequest/GetTaisysSimStatusAsync/{req_id}',
    updateSimDetail:'SRequest/UpdateSimDetailsAsync/{deviceIccid}',
    simDashboardCount: 'Inventory/GetSimStatusDashboard',
    simDashboardList: 'Inventory/SimInventoryDashboard',
    planCatByIccid:'DevicePlan/GetPlanCategoryListByIccid/{iccid}',

    // report api start here

    activationReport:'Report/ActivationReport'
}
